const gases = [
    {
        "gas_reading_number": 336496249,
        "location_number": 2491,
        "pod_serial_number": 2450611,
        "owner_number": 464,
        "reading_datestamp": "2022-01-20T17:15:00",
        "gas_p1": 10,
        "gas_p2": 900,
        "gas_p3": 3600,
        "gasprotocol_version": "V5.3",
        "battery_voltage": 3.2,
        "temperature_f": 20.3,
        "pressure": 1011.9,
        "humidity": 76.6,
        "noise_level": -1000,
        "peak_noise": -1000,
        "co_sensor_serial_number": "162681413",
        "co_state": "Reading",
        "co_prescaled": 289.89,
        "co_slope": 1,
        "co_offset": 0,
        "co_units": "ppb",
        "no_sensor_serial_number": "160511231",
        "no_state": "Reading",
        "no_prescaled": -2.54,
        "no_slope": 1,
        "no_offset": 0,
        "no_units": "ppb",
        "so2_sensor_serial_number": "164850921",
        "so2_state": "Reading",
        "so2_prescaled": 0,
        "so2_slope": 1,
        "so2_offset": 0,
        "so2_units": "ppb",
        "no2_sensor_serial_number": "202511324",
        "no2_state": "Reading",
        "no2_prescaled": 6.13,
        "no2_slope": 1,
        "no2_offset": 0,
        "no2_units": "ppb",
        "o3_sensor_serial_number": null,
        "o3_state": "Not Fitted",
        "o3_prescaled": -1000,
        "o3_slope": null,
        "o3_offset": null,
        "o3_units": "ppb",
        "h2s_sensor_serial_number": null,
        "h2s_state": "Not Fitted",
        "h2s_prescaled": -1000,
        "h2s_slope": null,
        "h2s_offset": null,
        "h2s_units": "ppb",
        "eo_sensor_serial_number": null,
        "eo_state": "Not Fitted",
        "eo_prescaled": -1000,
        "eo_slope": null,
        "eo_offset": null,
        "eo_units": "ppm",
        "uart_type": "CO2",
        "uart_sensor_serial_number": null,
        "uart_state": "Not Fitted",
        "uart_prescaled": -1000,
        "uart_slope": null,
        "uart_offset": null,
        "uart_units": "ppm",
        "aux1_sensor_serial_number": null,
        "aux1_type": "Not Fitted",
        "aux1_state": "Not Fitted",
        "aux1_prescaled": -1000,
        "aux1_slope": null,
        "aux1_offset": null,
        "aux1_units": null,
        "aux2_sensor_serial_number": null,
        "aux2_type": "Not Fitted",
        "aux2_state": "Not Fitted",
        "aux2_prescaled": -1000,
        "aux2_slope": null,
        "aux2_offset": null,
        "aux2_units": null,
        "aux3": 68,
        "aux4": 6
    },
    {
        "gas_reading_number": 336496250,
        "location_number": 2491,
        "pod_serial_number": 2450611,
        "owner_number": 464,
        "reading_datestamp": "2022-01-20T17:30:00",
        "gas_p1": 10,
        "gas_p2": 900,
        "gas_p3": 3600,
        "gasprotocol_version": "V5.3",
        "battery_voltage": 3.2,
        "temperature_f": 20.5,
        "pressure": 1011.9,
        "humidity": 77.2,
        "noise_level": -1000,
        "peak_noise": -1000,
        "co_sensor_serial_number": "162681413",
        "co_state": "Reading",
        "co_prescaled": 286.91,
        "co_slope": 1,
        "co_offset": 0,
        "co_units": "ppb",
        "no_sensor_serial_number": "160511231",
        "no_state": "Reading",
        "no_prescaled": -1.36,
        "no_slope": 1,
        "no_offset": 0,
        "no_units": "ppb",
        "so2_sensor_serial_number": "164850921",
        "so2_state": "Reading",
        "so2_prescaled": 0,
        "so2_slope": 1,
        "so2_offset": 0,
        "so2_units": "ppb",
        "no2_sensor_serial_number": "202511324",
        "no2_state": "Reading",
        "no2_prescaled": 6.1,
        "no2_slope": 1,
        "no2_offset": 0,
        "no2_units": "ppb",
        "o3_sensor_serial_number": null,
        "o3_state": "Not Fitted",
        "o3_prescaled": -1000,
        "o3_slope": null,
        "o3_offset": null,
        "o3_units": "ppb",
        "h2s_sensor_serial_number": null,
        "h2s_state": "Not Fitted",
        "h2s_prescaled": -1000,
        "h2s_slope": null,
        "h2s_offset": null,
        "h2s_units": "ppb",
        "eo_sensor_serial_number": null,
        "eo_state": "Not Fitted",
        "eo_prescaled": -1000,
        "eo_slope": null,
        "eo_offset": null,
        "eo_units": "ppm",
        "uart_type": "CO2",
        "uart_sensor_serial_number": null,
        "uart_state": "Not Fitted",
        "uart_prescaled": -1000,
        "uart_slope": null,
        "uart_offset": null,
        "uart_units": "ppm",
        "aux1_sensor_serial_number": null,
        "aux1_type": "Not Fitted",
        "aux1_state": "Not Fitted",
        "aux1_prescaled": -1000,
        "aux1_slope": null,
        "aux1_offset": null,
        "aux1_units": null,
        "aux2_sensor_serial_number": null,
        "aux2_type": "Not Fitted",
        "aux2_state": "Not Fitted",
        "aux2_prescaled": -1000,
        "aux2_slope": null,
        "aux2_offset": null,
        "aux2_units": null,
        "aux3": 66,
        "aux4": 6
    },
    {
        "gas_reading_number": 336496251,
        "location_number": 2491,
        "pod_serial_number": 2450611,
        "owner_number": 464,
        "reading_datestamp": "2022-01-20T17:45:00",
        "gas_p1": 10,
        "gas_p2": 900,
        "gas_p3": 3600,
        "gasprotocol_version": "V5.3",
        "battery_voltage": 3.2,
        "temperature_f": 20.8,
        "pressure": 1012.1,
        "humidity": 76.5,
        "noise_level": -1000,
        "peak_noise": -1000,
        "co_sensor_serial_number": "162681413",
        "co_state": "Reading",
        "co_prescaled": 286.42,
        "co_slope": 1,
        "co_offset": 0,
        "co_units": "ppb",
        "no_sensor_serial_number": "160511231",
        "no_state": "Reading",
        "no_prescaled": -2.14,
        "no_slope": 1,
        "no_offset": 0,
        "no_units": "ppb",
        "so2_sensor_serial_number": "164850921",
        "so2_state": "Reading",
        "so2_prescaled": 0,
        "so2_slope": 1,
        "so2_offset": 0,
        "so2_units": "ppb",
        "no2_sensor_serial_number": "202511324",
        "no2_state": "Reading",
        "no2_prescaled": 6.3,
        "no2_slope": 1,
        "no2_offset": 0,
        "no2_units": "ppb",
        "o3_sensor_serial_number": null,
        "o3_state": "Not Fitted",
        "o3_prescaled": -1000,
        "o3_slope": null,
        "o3_offset": null,
        "o3_units": "ppb",
        "h2s_sensor_serial_number": null,
        "h2s_state": "Not Fitted",
        "h2s_prescaled": -1000,
        "h2s_slope": null,
        "h2s_offset": null,
        "h2s_units": "ppb",
        "eo_sensor_serial_number": null,
        "eo_state": "Not Fitted",
        "eo_prescaled": -1000,
        "eo_slope": null,
        "eo_offset": null,
        "eo_units": "ppm",
        "uart_type": "CO2",
        "uart_sensor_serial_number": null,
        "uart_state": "Not Fitted",
        "uart_prescaled": -1000,
        "uart_slope": null,
        "uart_offset": null,
        "uart_units": "ppm",
        "aux1_sensor_serial_number": null,
        "aux1_type": "Not Fitted",
        "aux1_state": "Not Fitted",
        "aux1_prescaled": -1000,
        "aux1_slope": null,
        "aux1_offset": null,
        "aux1_units": null,
        "aux2_sensor_serial_number": null,
        "aux2_type": "Not Fitted",
        "aux2_state": "Not Fitted",
        "aux2_prescaled": -1000,
        "aux2_slope": null,
        "aux2_offset": null,
        "aux2_units": null,
        "aux3": 70,
        "aux4": 6
    },
    {
        "gas_reading_number": 336496252,
        "location_number": 2491,
        "pod_serial_number": 2450611,
        "owner_number": 464,
        "reading_datestamp": "2022-01-20T18:00:00",
        "gas_p1": 10,
        "gas_p2": 900,
        "gas_p3": 3600,
        "gasprotocol_version": "V5.3",
        "battery_voltage": 3.2,
        "temperature_f": 21,
        "pressure": 1011.7,
        "humidity": 76.1,
        "noise_level": -1000,
        "peak_noise": -1000,
        "co_sensor_serial_number": "162681413",
        "co_state": "Reading",
        "co_prescaled": 287.62,
        "co_slope": 1,
        "co_offset": 0,
        "co_units": "ppb",
        "no_sensor_serial_number": "160511231",
        "no_state": "Reading",
        "no_prescaled": -1.04,
        "no_slope": 1,
        "no_offset": 0,
        "no_units": "ppb",
        "so2_sensor_serial_number": "164850921",
        "so2_state": "Reading",
        "so2_prescaled": 0,
        "so2_slope": 1,
        "so2_offset": 0,
        "so2_units": "ppb",
        "no2_sensor_serial_number": "202511324",
        "no2_state": "Reading",
        "no2_prescaled": 6.12,
        "no2_slope": 1,
        "no2_offset": 0,
        "no2_units": "ppb",
        "o3_sensor_serial_number": null,
        "o3_state": "Not Fitted",
        "o3_prescaled": -1000,
        "o3_slope": null,
        "o3_offset": null,
        "o3_units": "ppb",
        "h2s_sensor_serial_number": null,
        "h2s_state": "Not Fitted",
        "h2s_prescaled": -1000,
        "h2s_slope": null,
        "h2s_offset": null,
        "h2s_units": "ppb",
        "eo_sensor_serial_number": null,
        "eo_state": "Not Fitted",
        "eo_prescaled": -1000,
        "eo_slope": null,
        "eo_offset": null,
        "eo_units": "ppm",
        "uart_type": "CO2",
        "uart_sensor_serial_number": null,
        "uart_state": "Not Fitted",
        "uart_prescaled": -1000,
        "uart_slope": null,
        "uart_offset": null,
        "uart_units": "ppm",
        "aux1_sensor_serial_number": null,
        "aux1_type": "Not Fitted",
        "aux1_state": "Not Fitted",
        "aux1_prescaled": -1000,
        "aux1_slope": null,
        "aux1_offset": null,
        "aux1_units": null,
        "aux2_sensor_serial_number": null,
        "aux2_type": "Not Fitted",
        "aux2_state": "Not Fitted",
        "aux2_prescaled": -1000,
        "aux2_slope": null,
        "aux2_offset": null,
        "aux2_units": null,
        "aux3": 72,
        "aux4": 6
    }
];

module.exports.gases = gases;
