const gases = [
    {
        "gas_reading_number": 89357746,
        "location_number": 915,
        "pod_serial_number": 2410103,
        "owner_number": 21,
        "reading_datestamp": new Date,
        "gas_p1": 10,
        "gas_p2": 60,
        "gas_p3": 600,
        "gasprotocol_version": "V5.1",
        "battery_voltage": 3.3,
        "temperature_f": 40.8,
        "pressure": 1001.6,
        "humidity": 77.3,
        "noise_level": -1000,
        "peak_noise": -1000,
        "co_sensor_serial_number": null,
        "co_state": "Reading",
        "co_prescaled": 1,
        "co_slope": null,
        "co_offset": null,
        "co_units": "ppb",
        "no_sensor_serial_number": "160140537",
        "no_state": "Reading",
        "no_prescaled": 53.51,
        "no_slope": 1,
        "no_offset": 0,
        "no_units": "ppb",
        "so2_sensor_serial_number": null,
        "so2_state": "Reading",
        "so2_prescaled": 1,
        "so2_slope": null,
        "so2_offset": null,
        "so2_units": "ppb",
        "no2_sensor_serial_number": "202641142",
        "no2_state": "Reading",
        "no2_prescaled": 17.08,
        "no2_slope": 1,
        "no2_offset": 0,
        "no2_units": "ppb",
        "o3_sensor_serial_number": "204641031",
        "o3_state": "Reading",
        "o3_prescaled": -7.58,
        "o3_slope": 1,
        "o3_offset": 0,
        "o3_units": "ppb",
        "h2s_sensor_serial_number": null,
        "h2s_state": "Reading",
        "h2s_prescaled": 1,
        "h2s_slope": null,
        "h2s_offset": null,
        "h2s_units": "ppb",
        "eo_sensor_serial_number": null,
        "eo_state": "Reading",
        "eo_prescaled": 1,
        "eo_slope": null,
        "eo_offset": null,
        "eo_units": "ppm",
        "uart_type": "CO2",
        "uart_sensor_serial_number": null,
        "uart_state": "Not Fitted",
        "uart_prescaled": -1000,
        "uart_slope": null,
        "uart_offset": null,
        "uart_units": "ppm",
        "aux1_sensor_serial_number": null,
        "aux1_type": "Not Fitted",
        "aux1_state": "Not Fitted",
        "aux1_prescaled": -1000,
        "aux1_slope": null,
        "aux1_offset": null,
        "aux1_units": null,
        "aux2_sensor_serial_number": null,
        "aux2_type": "Not Fitted",
        "aux2_state": "Not Fitted",
        "aux2_prescaled": -1000,
        "aux2_slope": null,
        "aux2_offset": null,
        "aux2_units": null,
        "aux3": 535,
        "aux4": 1483
    },
];

module.exports.gases = gases;
