const pms = [
    {
        "particle_reading_number": 22989756,
        "location_number": 915,
        "pod_serial_number": 2410103,
        "owner_number": 21,
        "reading_datestamp": new Date,
        "particle_p1": 30,
        "particle_p2": 60,
        "particle_p3": 600,
        "particleprotocol_version": "v3.0",
        "reading_status": "OK",
        "battery_voltage": 3.3,
        "battery_low": false,
        "super_cap_voltage": 4.9,
        "temperature_f": 37.4,
        "humidity": 77,
        "pressure": 1015.6,
        "particle_modem_overlap": true,
        "pm10_prescale": 16.32,
        "pm10_slope": 1,
        "pm10_offset": 0,
        "pm_course_prescale": -1000,
        "pm_course_slope": 1,
        "pm_course_offset": 0,
        "pm4_prescale": 14.98,
        "pm4_slope": 1,
        "pm4_offset": 0,
        "pm2_5_prescale": 11.8,
        "pm2_5_slope": 1,
        "pm2_5_offset": 0,
        "pm1_prescale": 7.3,
        "pm1_slope": 1,
        "pm1_offset": 0,
        "pm_total_prescale": 16.32,
        "pm_total_slope": 1,
        "pm_total_offset": 0
    },
]

module.exports.pms = pms;
